/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.spring.io/snapshot")
    }

    maven {
        url = uri("https://repo.spring.io/milestone")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.springframework.ai.spring.ai.starter.model.openai)
    api(libs.org.springframework.ai.spring.ai.vector.store)
    api(libs.org.springframework.boot.spring.boot.starter.actuator)
    api(libs.org.springframework.boot.spring.boot.starter.cache)
    api(libs.org.springframework.boot.spring.boot.starter.data.jpa)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springframework.boot.spring.boot.starter.validation)
    api(libs.org.springframework.boot.spring.boot.starter.thymeleaf)
    implementation("org.springframework.security:spring-security-crypto:6.2.7")
    api(libs.javax.cache.cache.api)
    api(libs.com.github.ben.manes.caffeine.caffeine)
    api(libs.org.webjars.webjars.locator.lite)
    api(libs.org.webjars.npm.bootstrap)
    api(libs.org.webjars.npm.font.awesome)
    api(libs.org.webjars.npm.marked)
    api(libs.jakarta.xml.bind.jakarta.xml.bind.api)
    api(libs.org.springdoc.springdoc.openapi.starter.webmvc.ui)
    runtimeOnly(libs.com.h2database.h2)
    runtimeOnly(libs.com.mysql.mysql.connector.j)
    runtimeOnly(libs.org.postgresql.postgresql)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.springframework.boot.spring.boot.devtools)
    testImplementation(libs.org.springframework.boot.spring.boot.testcontainers)
    testImplementation(libs.org.springframework.boot.spring.boot.docker.compose)
    testImplementation(libs.org.testcontainers.junit.jupiter)
    testImplementation(libs.org.testcontainers.mysql)
}

group = "org.springframework.samples"
version = "3.5.0-SNAPSHOT"
description = "petclinic"
java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
