# database init, supports postgres too
database=postgres
# Wenn keine POSTGRES_URL gesetzt ist, verwenden wir lokal eine H2 In-Memory DB
spring.datasource.url=${POSTGRES_URL:jdbc:h2:mem:petclinic;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${POSTGRES_USER:root}
spring.datasource.password=${POSTGRES_PASSWORD:}
# SQL ist idempotent, daher sicher zum wiederholten Ausführen
spring.sql.init.mode=always
spring.docker.compose.enabled=false
